version: '2'
services:
    mediahype-app:
        image: mediahype
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://mediahype-postgresql:5432/MediaHype
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_JEST_URI=http://mediahype-elasticsearch:9200
        ports:
            - 8080:8080
    mediahype-postgresql:
        extends:
            file: postgresql.yml
            service: mediahype-postgresql
    mediahype-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: mediahype-elasticsearch
